### ISSUE TITLE
The class processing.core.PGraphicsJava2D does not exist

### ISSUE THREAD

**Issue by Lord-of-the-Galaxy** [danbernier/WordCram#68]
I get this error:  
`ClassNotFoundException: processing.core.PGraphicsJava2D`  
And for no apparent reason. The class obviously exists, yet it says it does not. I installed the latest version, and ran the helloworld example.

**Comment by Lord-of-the-Galaxy** [comment]
Latest version works, sorry. Older ones dont.

**Comment by danbernier** [comment]
Yep, the internal Processing classes that WordCram relies on have changed
over the years, as Processing has changed, so older versions of WordCram
don't work. Glad you made it through!

~
This message was made with 100% thumbs.

**Comment by Lord-of-the-Galaxy** [comment]
Then that's done. Thanks!
