### ISSUE TITLE
Broken link to block on FAQ

### ISSUE THREAD

**Issue by jhirbour** [danbernier/WordCram#71]
The FAQ (https://github.com/danbernier/WordCram/wiki/FAQ) links to http://wordcram.org/2013/03/02/why-dont-all-my-words-show-up/ which 404s.

**Comment by danbernier** [comment]
Fixed! I must've broken the links when I upgraded the blog at some point, thanks for telling me.

Here's the post, if you're curious: http://wordcram.org/2013/03/03/why-dont-all-my-words-show-up.html
